# Generated by Django 4.1.3 on 2022-11-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_id", models.CharField(max_length=200)),
                ("customer_id", models.CharField(max_length=200)),
                ("order_id", models.CharField(max_length=200)),
                ("payment_id", models.CharField(max_length=200)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
