# Generated by Django 4.1.3 on 2022-11-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_payments", "0002_customer_order_shop_remove_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_id",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="main_payments.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shop_id",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="main_payments.shop",
            ),
            preserve_default=False,
        ),
    ]
